baseurl = "https://yewton.net/"
languageCode = "ja-jp"
title = "yewton.net"
# Enable comments by entering your Disqus shortname
disqusShortname = "yewton"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-72312909-1"
# Define the number of posts per site
paginate = 10
canonifyurls = true
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus"
hasCJKLanguage = true

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    # Tell me who you are
    author = "yewton"
    bio = "だらだらしたい。"
    location = "Tokyo, Japan"
    site_description = "開発的な話とか日常の駄文、その他もろもろ。"
    copyright  = "yewton. Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    gravatar = "yewton@gmail.com"

    # Format dates with Go's time formatting
    date_format = "2006.01.02 Mon"
    birthday = "1986-06-11"

[[params.anniversary]]
    prefix = "結婚"
    date = "2010-11-30"
    suffix = "目"

[[params.anniversary]]
    prefix = "付き合って"
    date = "2007-11-30"
    suffix = "目"

[[params.anniversary]]
    prefix = "社会人"
    date = "2010-04-01"
    suffix = "目"

[[params.anniversary]]
    prefix = "現職勤続"
    date = "2015-09-01"
    suffix = ""

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/yewton"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = "yewton"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = "yewton"
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "yewton"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = "YutoSasaki"
    facebook        = "yewton"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "yewton"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
